### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ieee488** [MajicDesigns/MD_MAX72XX#14] opened 2019-04-11 13:50 UTC
I don't pretend to know how Github works

The link to MD_MAX72xx.h  on https://majicdesigns.github.io/MD_MAX72XX/page_software.html  is broken

All the links on https://majicdesigns.github.io/MD_MAX72XX/files.html  are broken

All the links on https://majicdesigns.github.io/MD_MAX72XX/globals.html   are broken

.

**Comment by MajicDesigns** [comment] 2019-04-11 20:19
If you have the library installed you should have a duplicate of this doc in the MD_MAX72XX/docs folder (open index.html). Local version works on my system - does it work locally for you?

**Comment by ieee488** [comment] 2019-04-11 20:47
Yes, the local version works.

The online version is broken.

**Comment by MajicDesigns** [comment] 2019-04-11 22:08
Looks like this is a problem broken for every other repository as well. I'll note it but can't understand what to do about it for the moment.

**Closed as completed by MajicDesigns** 2019-04-11 22:08 UTC
Labels: bug
